import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Users, Coins, Trophy, X } from 'lucide-react';
import { Card } from '../ui/Card';
export function FantasyTeamCard({ team, onRemovePick, readonly }) {
    const activePicks = team.picks.filter((p) => p.isActive);
    const drivers = activePicks.filter((p) => p.type === 'driver');
    const constructors = activePicks.filter((p) => p.type === 'constructor');
    return (_jsxs(Card, { children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-2xl font-bold text-white", children: team.name }), _jsx("p", { className: "text-gray-400 text-sm mt-1", children: "Tu Equipo Fant\u00E1stico" })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsxs("div", { className: "text-right", children: [_jsxs("div", { className: "flex items-center gap-1 text-yellow-400", children: [_jsx(Coins, { className: "w-4 h-4" }), _jsx("span", { className: "font-bold text-lg", children: team.budget.toFixed(1) })] }), _jsx("p", { className: "text-xs text-gray-500", children: "Presupuesto" })] }), _jsxs("div", { className: "text-right", children: [_jsxs("div", { className: "flex items-center gap-1 text-f1-red", children: [_jsx(Trophy, { className: "w-4 h-4" }), _jsx("span", { className: "font-bold text-lg", children: team.totalScore.toFixed(1) })] }), _jsx("p", { className: "text-xs text-gray-500", children: "Puntos" })] })] })] }), _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx(Users, { className: "w-4 h-4 text-gray-400" }), _jsxs("h3", { className: "text-sm font-semibold text-gray-300 uppercase tracking-wider", children: ["Pilotos (", drivers.length, "/5)"] })] }), _jsxs("div", { className: "space-y-2", children: [drivers.map((pick) => (_jsx(PickRow, { pick: pick, onRemove: onRemovePick, readonly: readonly }, pick.id))), drivers.length === 0 && (_jsx("p", { className: "text-gray-600 text-sm italic", children: "Sin pilotos seleccionados" }))] })] }), _jsxs("div", { children: [_jsx("div", { className: "flex items-center gap-2 mb-2", children: _jsxs("h3", { className: "text-sm font-semibold text-gray-300 uppercase tracking-wider", children: ["Constructor (", constructors.length, "/1)"] }) }), _jsxs("div", { className: "space-y-2", children: [constructors.map((pick) => (_jsx(PickRow, { pick: pick, onRemove: onRemovePick, readonly: readonly }, pick.id))), constructors.length === 0 && (_jsx("p", { className: "text-gray-600 text-sm italic", children: "Sin constructor seleccionado" }))] })] })] })] }));
}
function PickRow({ pick, onRemove, readonly }) {
    return (_jsxs("div", { className: "flex items-center justify-between bg-f1-gray-dark rounded-lg px-4 py-2.5", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-2 h-2 rounded-full bg-f1-red" }), _jsxs("div", { children: [_jsx("p", { className: "text-white text-sm font-medium", children: pick.type === 'driver' ? `Driver #${pick.driverId?.slice(0, 8)}` : `Constructor #${pick.teamId?.slice(0, 8)}` }), _jsx("p", { className: "text-xs text-gray-500", children: pick.type })] })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs("span", { className: "text-yellow-400 font-semibold text-sm", children: [pick.cost.toFixed(1), "M"] }), !readonly && onRemove && (_jsx("button", { onClick: () => onRemove(pick.id), className: "text-gray-500 hover:text-red-400 transition-colors", children: _jsx(X, { className: "w-4 h-4" }) }))] })] }));
}
//# sourceMappingURL=FantasyTeamCard.js.map