const countryFlags: Record<string, string> = {
  'Abu Dhabi': '🇦🇪',
  'Argentina': '🇦🇷',
  'Australia': '🇦🇺',
  'Austria': '🇦🇹',
  'Azerbaijan': '🇦🇿',
  'Bahrain': '🇧🇭',
  'Belgium': '🇧🇪',
  'Brazil': '🇧🇷',
  'Canada': '🇨🇦',
  'China': '🇨🇳',
  'Denmark': '🇩🇰',
  'Europe': '🇪🇺',
  'Finland': '🇫🇮',
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Great Britain': '🇬🇧',
  'Hungary': '🇭🇺',
  'India': '🇮🇳',
  'Italy': '🇮🇹',
  'Japan': '🇯🇵',
  'Korea': '🇰🇷',
  'Malaysia': '🇲🇾',
  'Mexico': '🇲🇽',
  'Monaco': '🇲🇨',
  'Morocco': '🇲🇦',
  'Netherlands': '🇳🇱',
  'New Zealand': '🇳🇿',
  'Portugal': '🇵🇹',
  'Qatar': '🇶🇦',
  'Russia': '🇷🇺',
  'Saudi Arabia': '🇸🇦',
  'Singapore': '🇸🇬',
  'South Africa': '🇿🇦',
  'Spain': '🇪🇸',
  'Sweden': '🇸🇪',
  'Switzerland': '🇨🇭',
  'Turkey': '🇹🇷',
  'United Arab Emirates': '🇦🇪',
  'United Kingdom': '🇬🇧',
  'United States': '🇺🇸',
  'USA': '🇺🇸',
  'Vietnam': '🇻🇳',
};

export function getFlagEmoji(country: string): string {
  return countryFlags[country] || '🏁';
}
